[build]
  publish = "dist"
  command = "echo 'Netlify Functions build complete'"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=/opt/buildhome/.nodejs/node_global"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["hono"]

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'none'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"
    Cache-Control = "s-maxage=300, stale-while-revalidate=60"
    X-API-Version = "2.0.0"
    X-Service-Type = "backend-api"
    X-Powered-By = "UNM-Server-V2-Backend-API"

[[headers]]
  for = "/.netlify/functions/api"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[dev]
  command = "pnpm start"
  port = 5678
  publish = "dist"
  functions = "netlify/functions"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
